In [3]:
import pandas as pd

# Datei laden (ersetze den Dateinamen durch den tatsächlichen Pfad zu deiner Datei)
pfad = "D:\\awrDATEN\\lena\\DATA SCIENCE INSTITUTE\\abschlussprojekt_Buchmarkt\\Analyse_vorhersage_Bestseller_LW\\Option_03\\bookPublishingData.csv"
df = pd.read_csv(pfad)
# Ersten Blick auf die Daten werfen
print(df.head(5))  # zeigt die ersten 5 Zeilen

# (optional) Infos zum DataFrame anzeigen
print(df.info())
df

   Publishing_Year                        Book_Name  \
0           1975.0                          Beowulf
1           1987.0                 Batman: Year One
2           2015.0                Go Set a Watchman
3           2008.0  When You Are Engulfed in Flames
4           2011.0         Daughter of Smoke & Bone

                                              Author Language_Code  \
0                             Unknown, Seamus Heaney         en-US
1  Frank Miller, David Mazzucchelli, Richmond Lew...           eng
2                                         Harper Lee           eng
3                                      David Sedaris         en-US
4                                       Laini Taylor           eng

  Author_Rating  Book_Average_Rating  Book_Ratings_Count          Genre  \
0        Novice                 3.42              155903  genre fiction
1  Intermediate                 4.23              145267  genre fiction
2        Novice                 3.31              138669  genre fiction
3  Intermediate                 4.04              150898        fiction
4  Intermediate                 4.04              198283  genre fiction

   Gross_Sales  Publisher_Revenue  Sale_Price  Sale_Rank  \
0      34160.0            20496.0        4.88          1
1      12437.5             7462.5        1.99          2
2      47795.0            28677.0        8.69          3
3      41250.0            24750.0        7.50          3
4      37952.5            22771.5        7.99          4

                        Publisher  Units_Sold
0        HarperCollins Publishers        7000
1        HarperCollins Publishers        6250
2  Amazon Digital Services,  Inc.        5500
3             Hachette Book Group        5500
4         Penguin Group (USA) LLC        4750
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Publishing_Year      1069 non-null   float64
 1   Book_Name            1047 non-null   object
 2   Author               1070 non-null   object
 3   Language_Code        1017 non-null   object
 4   Author_Rating        1070 non-null   object
 5   Book_Average_Rating  1070 non-null   float64
 6   Book_Ratings_Count   1070 non-null   int64
 7   Genre                1070 non-null   object
 8   Gross_Sales          1070 non-null   float64
 9   Publisher_Revenue    1070 non-null   float64
 10  Sale_Price           1070 non-null   float64
 11  Sale_Rank            1070 non-null   int64
 12  Publisher            1070 non-null   object
 13  Units_Sold           1070 non-null   int64
dtypes: float64(5), int64(3), object(6)
memory usage: 117.2+ KB
None

,Publishing_Year,Book_Name,Author,Language_Code,Author_Rating,Book_Average_Rating,Book_Ratings_Count,Genre,Gross_Sales,Publisher_Revenue,Sale_Price,Sale_Rank,Publisher,Units_Sold
0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.00,20496.000,4.88,1,HarperCollins Publishers,7000
1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.50,7462.500,1.99,2,HarperCollins Publishers,6250
2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.00,28677.000,8.69,3,"Amazon Digital Services, Inc.",5500
3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.00,24750.000,7.50,3,Hachette Book Group,5500
4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.50,22771.500,7.99,4,Penguin Group (USA) LLC,4750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2014.0,Gray Mountain,John Grisham,eng,Intermediate,3.52,37379,nonfiction,104.94,62.964,0.99,1268,"Amazon Digital Services, Inc.",106
1066,1989.0,The Power of One,Bryce Courtenay,eng,Excellent,4.34,57312,genre fiction,846.94,508.164,7.99,1270,Random House LLC,106
1067,1930.0,The Maltese Falcon,Dashiell Hammett,eng,Intermediate,3.92,58742,genre fiction,846.94,508.164,7.99,1271,Hachette Book Group,106
1068,2011.0,Night Road,Kristin Hannah,en-US,Excellent,4.17,58028,genre fiction,104.94,62.964,0.99,1272,"Amazon Digital Services, Inc.",106
1069,1999.0,Tripwire,Lee Child,eng,Excellent,4.07,55251,genre fiction,316.94,0.000,2.99,1273,"Amazon Digital Services, Inc.",106